### ISSUE TITLE
Exception at sending chat message

### ISSUE THREAD

**Issue by Lichthagel** [FabioZumbi12/UltimateChat-Sponge#1]
When someone sends a message in the chat I always get this exception:

``
[11:04:15] [Server thread/ERROR] [Sponge/]: Could not pass ServerChatEvent to Plugin{id=ultimatechat, name=UltimateChat, version=1.7.0, description=Complete and advanced chat plugin, authors=[FabioZumbi12], source=/home/verwaltung/Minecraft/Bermuda2/mods/UltimateChat-1.7.0-b9.jar}
java.lang.NullPointerException
	at br.net.fabiozumbi12.UltimateChat.UCMessages.formatTags(UCMessages.java:481) ~[UCMessages.class:?]
	at br.net.fabiozumbi12.UltimateChat.UCMessages.sendMessage(UCMessages.java:334) ~[UCMessages.class:?]
	at br.net.fabiozumbi12.UltimateChat.UCMessages.sendFancyMessage(UCMessages.java:129) ~[UCMessages.class:?]
	at br.net.fabiozumbi12.UltimateChat.UCListener.onChat(UCListener.java:64) ~[UCListener.class:?]
	at org.spongepowered.common.event.listener.ChatListener_UCListener_onChat164.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2123-6.0.0-BETA-1902]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1902]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1902]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:105) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) [EventBus.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$zok000(NetHandlerPlayServer.java:82) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:897) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:135) [PacketUtil.class:1.10.2-2123-6.0.0-BETA-1902]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
``

I have the following mods and plugins installed:

``
[11:07:53] [Server thread/INFO]: Plugins (33): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, InfinityLib, AgriCraft, Bagginses, BiblioCraft, Chisel, Chisels & Bits, Craftable Saddles, Crossbow Mod, PTRModelLib, Decocraft, FoxCore, FoxGuard, HelpMe, Inventory Tweaks, mercurius_updater, Nucleus, Pam's HarvestCraft, CustomCommands, PermissionManager, PlaceholderAPI, PrimalCore, ProjectPortals, UltimateChat, UltimateCore, StatusProtocol, VoxelSniper, WorldEdit
``

Please fix fast, thanks.

**Comment by leelawd** [comment]
Just mentioning, this was an issue with PermissionManager 2.6.* which has been updated to 3.0.0 as of today. This is fixed as of 3.0.0
